### PR TITLE
fix: Processing LDEPF, closes #498, RSR-1238

### LINKED ISSUE #498: Processing LDEPF
**Subject of the issue**

When precessing Digital channel, the ExtRef@desc must begins with `DYN_LDEPF_DIGITAL CHANNEL`  ..  ` BOOLEAN_` instead of  `DYN_LDEPF_DIGITAL CHANNEL`  ..  ` BOOLEEN_` .
In addition when we set the `ChannelLevMod` or `ChannelLevModq` attributes to `NA` for Channels, that should not throw error.

**Your environment**

* Version of CoMPAS : `0.2.41`

### PR DESCRIPTION
**Pull request by samirromdhani**
fix #498

### CODE REVIEW

File: sct-commons/src/main/java/org/lfenergy/compas/sct/commons/ExtRefEditorService.java [hunk 1]
```diff
@@ -334,38 +341,38 @@ private void updateLDEPFExtRefBinding(TExtRef extRef, TIED iedSource, TChannel s
...
+            case SETVAL_DA_NAME -> {
+                if(LN_PREFIX_B.equals(lnAdapter.getPrefix()) || LN_PREFIX_A.equals(lnAdapter.getPrefix())){
+                    yield setting.isSetChannelLevModQ() && !setting.getChannelLevModQ().equals(TChannelLevMod.NA) ? setting.getChannelLevModQ().value(): null;
+                } else {
+                    yield setting.isSetChannelLevMod() && !setting.getChannelLevMod().equals(TChannelLevMod.NA) ? setting.getChannelLevMod().value(): null;
+                }
+            }
             case STVAL_DA_NAME -> ActiveStatus.ON.getValue();
             case SETSRCREF_DA_NAME -> computeDaiValue(lnAdapter, extRef, setting.getDAName());
             default -> null;
```
Comment (gleizesDor) [inline sct-commons/src/main/java/org/lfenergy/compas/sct/commons/ExtRefEditorService.java:373]: if we run the `DO_DA_MAPPINGS` List, there are only 4 values, so this should be an exception; 
```java
default -> throw new IllegalStateException("Unexpected value: " + doDaName.daName);
```

File: sct-commons/src/main/java/org/lfenergy/compas/sct/commons/ExtRefEditorService.java [hunk 2]
```diff
@@ -334,38 +341,38 @@ private void updateLDEPFExtRefBinding(TExtRef extRef, TIED iedSource, TChannel s
 
     private List<SclReportItem> updateLDEPFDos(LDeviceAdapter lDeviceAdapter, TExtRef extRef, TChannel setting) {
```
Comment (gleizesDor) [inline sct-commons/src/main/java/org/lfenergy/compas/sct/commons/ExtRefEditorService.java:342]: final result should be : 
```java
private void updateLDEPFDos(LDeviceAdapter lDeviceAdapter, TExtRef extRef, TChannel setting) {
        if (setting.getChannelType().equals(TChannelType.DIGITAL)) {
            //digital
            lDeviceAdapter.findLnAdapter(LN_RBDR, setting.getChannelNum(), null)
                    .ifPresent(lnAdapter -> DO_DA_MAPPINGS.forEach(doNameAndDaName -> updateVal(lnAdapter, doNameAndDaName, extRef, setting)));
            lDeviceAdapter.findLnAdapter(LN_RBDR, setting.getChannelNum(), LN_PREFIX_B)
                    .ifPresent(lnAdapter -> DO_DA_MAPPINGS.forEach(doNameAndDaName -> updateVal(lnAdapter, doNameAndDaName, extRef, setting)));
        }
        if (setting.getChannelType().equals(TChannelType.ANALOG)) {
            //analog
            lDeviceAdapter.findLnAdapter(LN_RADR, setting.getChannelNum(), null)
                    .ifPresent(lnAdapter -> DO_DA_MAPPINGS.forEach(doNameAndDaName -> updateVal(lnAdapter, doNameAndDaName, extRef, setting)));
            lDeviceAdapter.findLnAdapter(LN_RADR, setting.getChannelNum(), LN_PREFIX_A)
                    .ifPresent(lnAdapter -> DO_DA_MAPPINGS.forEach(doNameAndDaName -> updateVal(lnAdapter, doNameAndDaName, extRef, setting)));
        }
    }
```

File: sct-commons/src/main/java/org/lfenergy/compas/sct/commons/ExtRefEditorService.java [hunk 3]
```diff
@@ -334,38 +341,38 @@ private void updateLDEPFExtRefBinding(TExtRef extRef, TIED iedSource, TChannel s
...
-                    .ifPresent(lnAdapter -> doNameAndDaNameList.forEach(doNameAndDaName -> updateVal(lnAdapter, doNameAndDaName.doName, doNameAndDaName.daName, extRef, setting).ifPresent(sclReportItems::add)));
+                    .ifPresent(lnAdapter -> DO_DA_MAPPINGS.forEach(doNameAndDaName -> updateVal(lnAdapter, doNameAndDaName.doName, doNameAndDaName.daName, extRef, setting).ifPresent(sclReportItems::add)));
             lDeviceAdapter.findLnAdapter(LN_RADR, setting.getChannelNum(), LN_PREFIX_A)
-                    .ifPresent(lnAdapter -> doNameAndDaNameList.forEach(doNameAndDaName -> updateVal(lnAdapter, doNameAndDaName.doName, doNameAndDaName.daName, extRef, setting).ifPresent(sclReportItems::add)));
+                    .ifPresent(lnAdapter -> DO_DA_MAPPINGS.forEach(doNameAndDaName -> updateVal(lnAdapter, doNameAndDaName.doName, doNameAndDaName.daName, extRef, setting).ifPresent(sclReportItems::add)));
         }
         return sclReportItems;
     }
 
     private Optional<SclReportItem> updateVal(AbstractLNAdapter<?> lnAdapter, String doName, String daName, TExtRef extRef, TChannel setting) {
```
Comment (gleizesDor) [inline sct-commons/src/main/java/org/lfenergy/compas/sct/commons/ExtRefEditorService.java:361]: final result should be : 
```java
private void updateVal(AbstractLNAdapter<?> lnAdapter, DoNameAndDaName doDaName, TExtRef extRef, TChannel setting) {
        String lnPrefix = lnAdapter.getPrefix();
        Optional<SclReportItem> sclReportItem = switch (doDaName.daName) {
            case DU_DA_NAME -> setting.isSetChannelShortLabel() ? lnAdapter.getDOIAdapterByName(doDaName.doName).updateDAI(doDaName.daName, setting.getChannelShortLabel()) :
                Optional.empty();
            case SETVAL_DA_NAME -> {
                if (LN_PREFIX_B.equals(lnPrefix) || LN_PREFIX_A.equals(lnPrefix)) {
                    yield setting.isSetChannelLevModQ() && !setting.getChannelLevModQ().equals(TChannelLevMod.NA) ? lnAdapter.getDOIAdapterByName(doDaName.doName).updateDAI(doDaName.daName, setting.getChannelLevModQ().value()) : Optional.empty();
                } else {
                    yield setting.isSetChannelLevMod() && !setting.getChannelLevMod().equals(TChannelLevMod.NA) ? lnAdapter.getDOIAdapterByName(doDaName.doName).updateDAI(doDaName.daName, setting.getChannelLevMod().value()) : Optional.empty();
                }
            }
            case STVAL_DA_NAME -> lnAdapter.getDOIAdapterByName(doDaName.doName).updateDAI(doDaName.daName, ActiveStatus.ON.getValue());
            case SETSRCREF_DA_NAME -> lnAdapter.getDOIAdapterByName(doDaName.doName).updateDAI(doDaName.daName, computeDaiValue(lnPrefix, extRef, setting.getDAName()));
            default -> throw new IllegalStateException("Unexpected value: " + doDaName.daName);
        };
        sclReportItem.ifPresent(errorHanlder::add);
    }
```

**Review by gleizesDor — APPROVED** [review]
