### PR TITLE
fix copySclElement - refactor manage monitoring lns (LGOS, LSVS), fixes #487

### LINKED ISSUE #487: LGOS and LSVS logical nodes error
**Subject of the issue**

When calling `manageMonitoringLns `:  the SCL file inwhich  LNs (LSVS and LGOS) should be updated and/or created in each LDevice LDSUIED'

**Your environment**

* Version of CoMPAS : `0.2.38`

**Steps to reproduce**

SCD file when LN with lnClass LGOS will be updated and when exist an SCL namespaced privates

**Expected behaviour**

No error occur

**Actual behaviour**

- `ScdException` with null message  with linked exception `UnmarshalException`:  `com.rte_france.rspace.rte_scl_xsd.commons.models.scl.TRTEPARAM is not known to this context`

Example of structure that cause error
```xml
<LN lnClass="LGOS" inst="1" lnType="RTE_8F9D058364DA6B12749A810E867DBBF5_LGOS_V1.0.0">
    <DOI name="GoCBRef">
        <Private type="RTE-PARAM">
<rte:RTEPARAM shortLabel="REF-GO-LGOS-1" longLabel="REFERENCE DU GOOSE SUPERVISE PAR LGOS 1" conf="true"/>
        </Private>
        <DAI name="d" valKind="RO" valImport="false">
<Val>Object reference of subscribed GOOSE control block</Val>
        </DAI>
        <DAI name="setSrcCB" valKind="RO" valImport="true"/>
        <DAI name="setSrcRef" valKind="RO" valImport="true"/>
    </DOI>
</LN>
````

### PR DESCRIPTION
**Pull request by samirromdhani**
https://github.com/com-pas/compas-sct/issues/487

### CODE REVIEW

File: sct-commons/src/main/java/org/lfenergy/compas/sct/commons/SclService.java [hunk 1]
```diff
@@ -197,12 +219,65 @@ public List<SclReportItem> updateDoInRef(SCL scd) {
...
+
+    private void manageMonitoringLns(List<TExtRef> tExtRefs, SCL scd, TIED tied, TLDevice tlDevice, String doName, MonitoringLnClassEnum monitoringLnClassEnum, JAXBContext jaxbContext) {
+        List<TLN> lnList = lnService.getFilteredLns(tlDevice, tln -> monitoringLnClassEnum.value().equals(tln.getLnClass().getFirst())).toList();
+        if (lnList.isEmpty())
+            errorHanlder.add(SclReportItem.warning(tied.getName()+"/"+tlDevice.getInst()+"/"+monitoringLnClassEnum.value(), "There is no LN %s present in LDevice".formatted(monitoringLnClassEnum.value())));
+        if (tExtRefs.isEmpty()) {
+            return;
+        }
+        DoLinkedToDaFilter doLinkedToDaFilter = new DoLinkedToDaFilter(doName, List.of(), DA_SETSRCREF, List.of());
+        lnList.forEach(tln -> dataTypeTemplateService.getFilteredDoLinkedToDa(scd.getDataTypeTemplates(), tln.getLnType(), doLinkedToDaFilter)
```
Comment (gleizesDor) [inline sct-commons/src/main/java/org/lfenergy/compas/sct/commons/SclService.java:248]: We should avoid these complicated methods;  
For the ExtRefs, we can inspire from this method : `com.rte_france.rspace.rconf.service.ExtRefsService#existsDoInLn` in RCONF

File: sct-commons/src/main/java/org/lfenergy/compas/sct/commons/SclService.java [hunk 2]
```diff
@@ -197,12 +219,65 @@ public List<SclReportItem> updateDoInRef(SCL scd) {
...
+                                    manageMonitoringLns(tExtRefs.stream().filter(tExtRef -> TServiceType.GOOSE.equals(tExtRef.getServiceType())).toList(), scd, tied, tlDevice, DO_GOCBREF, MonitoringLnClassEnum.LGOS, jaxbContext);
+                                    manageMonitoringLns(tExtRefs.stream().filter(tExtRef -> TServiceType.SMV.equals(tExtRef.getServiceType())).toList(), scd, tied, tlDevice, DO_SVCBREF, MonitoringLnClassEnum.LSVS, jaxbContext);
+                                }));
+        return errorHanlder;
+    }
+
+    private void manageMonitoringLns(List<TExtRef> tExtRefs, SCL scd, TIED tied, TLDevice tlDevice, String doName, MonitoringLnClassEnum monitoringLnClassEnum, JAXBContext jaxbContext) {
+        List<TLN> lnList = lnService.getFilteredLns(tlDevice, tln -> monitoringLnClassEnum.value().equals(tln.getLnClass().getFirst())).toList();
+        if (lnList.isEmpty())
+            errorHanlder.add(SclReportItem.warning(tied.getName()+"/"+tlDevice.getInst()+"/"+monitoringLnClassEnum.value(), "There is no LN %s present in LDevice".formatted(monitoringLnClassEnum.value())));
```
Comment (gleizesDor) [inline sct-commons/src/main/java/org/lfenergy/compas/sct/commons/SclService.java:243]: this the LDSUIED Ldevice, so we can replace `tlDevice.getInst()` by `LDEVICE_LDSUIED` everywhere

File: sct-commons/src/main/java/org/lfenergy/compas/sct/commons/SclService.java [hunk 3]
```diff
@@ -197,12 +219,65 @@ public List<SclReportItem> updateDoInRef(SCL scd) {
...
+        if (tExtRefs.isEmpty()) {
```
Comment (gleizesDor) [inline sct-commons/src/main/java/org/lfenergy/compas/sct/commons/SclService.java:244]: this check should have been done earlier

File: sct-commons/src/main/java/org/lfenergy/compas/sct/commons/SclService.java [hunk 4]
```diff
@@ -197,12 +219,65 @@ public List<SclReportItem> updateDoInRef(SCL scd) {
...
     @Override
-    public List<SclReportItem> manageMonitoringLns(SCL scd) {
-        SclRootAdapter sclRootAdapter = new SclRootAdapter(scd);
-        return sclRootAdapter.streamIEDAdapters()
-                .filter(iedAdapter -> !iedAdapter.getName().contains(IED_TEST_NAME))
-                .map(IEDAdapter::manageMonitoringLns)
-                .flatMap(List::stream)
+    public List<SclReportItem> manageMonitoringLns(SCL scd, JAXBContext jaxbContext) {
+        errorHanlder.clear();
+        List<TExtRef> tExtRefs =  scd.getIED().stream()
```
Comment (gleizesDor) [inline sct-commons/src/main/java/org/lfenergy/compas/sct/commons/SclService.java:224]: use indexed in order to not re-calculate all extRefs; 
```java
@Override
    public List<SclReportItem> manageMonitoringLns(SCL scd, JAXBContext jaxbContext) {
        errorHanlder.clear();
        Map<TServiceType, List<TExtRef>> serviceTypeToExtRefs = scd.getIED().stream()
                .flatMap(ldeviceService::getLdevices)
                .flatMap(extRefService::getExtRefs)
                .filter(tExtRef -> tExtRef.getServiceType().equals(TServiceType.GOOSE) || tExtRef.getServiceType().equals(TServiceType.SMV))
                .collect(Collectors.groupingBy(TExtRef::getServiceType));
        iedService.getFilteredIeds(scd, ied -> !ied.getName().contains(IED_TEST_NAME))
                        .forEach(tied ->
                                ldeviceService.findLdevice(tied, LDEVICE_LDSUIED)
                                .ifPresent(ldsuiedLdevice -> {
                                    Optional.ofNullable(serviceTypeToExtRefs.get(TServiceType.GOOSE))
                                                    .ifPresent(extRefs -> manageMonitoringLns(extRefs, scd, tied, ldsuiedLdevice, DO_GOCBREF, MonitoringLnClassEnum.LGOS, jaxbContext));
                                    Optional.ofNullable(serviceTypeToExtRefs.get(TServiceType.SMV))
                                                    .ifPresent(extRefs -> manageMonitoringLns(extRefs, scd, tied, ldsuiedLdevice, DO_SVCBREF, MonitoringLnClassEnum.LSVS, jaxbContext));
                                }));
        return errorHanlder;
    }
```

File: sct-commons/src/main/java/org/lfenergy/compas/sct/commons/SclService.java [hunk 5]
```diff
@@ -197,12 +219,65 @@ public List<SclReportItem> updateDoInRef(SCL scd) {
...
+                .flatMap(tied -> new LdeviceService(new LnService()).getLdevices(tied).flatMap(tlDevice -> Stream.of(tlDevice.getLN0())))
```
[the remark this answers is not in the document]
Comment (samirromdhani) [reply sct-commons/src/main/java/org/lfenergy/compas/sct/commons/SclService.java]: done

File: sct-commons/src/main/java/org/lfenergy/compas/sct/commons/SclService.java (hunk 2 above)
Comment (samirromdhani) [reply sct-commons/src/main/java/org/lfenergy/compas/sct/commons/SclService.java]: done

File: sct-commons/src/main/java/org/lfenergy/compas/sct/commons/SclService.java [hunk 6]
```diff
@@ -197,12 +219,65 @@ public List<SclReportItem> updateDoInRef(SCL scd) {
...
+                .filter(TAnyLN::isSetInputs)
+                .flatMap(ln0 -> ln0.getInputs().getExtRef().stream())
+                .filter(tExtRef -> tExtRef.isSetServiceType() && tExtRef.isSetSrcCBName())
+                .toList();
+        iedService.getFilteredIeds(scd, ied -> !ied.getName().contains(IED_TEST_NAME))
+                        .forEach(tied ->
+                                ldeviceService.findLdevice(tied, tlDevice -> LDEVICE_LDSUIED.equals(tlDevice.getInst()))
```
[the remark this answers is not in the document]
Comment (samirromdhani) [reply sct-commons/src/main/java/org/lfenergy/compas/sct/commons/SclService.java]: done

File: sct-commons/src/main/java/org/lfenergy/compas/sct/commons/SclService.java (hunk 3 above)
Comment (samirromdhani) [reply sct-commons/src/main/java/org/lfenergy/compas/sct/commons/SclService.java]: done

File: sct-commons/src/main/java/org/lfenergy/compas/sct/commons/SclService.java [hunk 7]
```diff
@@ -196,13 +219,70 @@ public List<SclReportItem> updateDoInRef(SCL scd) {
...
-                .flatMap(List::stream)
+    public List<SclReportItem> manageMonitoringLns(SCL scd, JAXBContext jaxbContext) {
+        errorHanlder.clear();
+        iedService.getFilteredIeds(scd, ied -> !ied.getName().contains(IED_TEST_NAME))
+                        .forEach(tied -> {
+                            List<TExtRef> tExtRefs = ldeviceService.getLdevices(tied)
+                                    .flatMap(tlDevice -> extRefReaderService.getExtRefs(tlDevice.getLN0()))
+                                    .filter(tExtRef -> tExtRef.isSetServiceType() && tExtRef.isSetSrcCBName()
+                                            && (tExtRef.getServiceType().equals(TServiceType.GOOSE) || tExtRef.getServiceType().equals(TServiceType.SMV)))
+                                    .toList();
```
Comment (gleizesDor) [inline sct-commons/src/main/java/org/lfenergy/compas/sct/commons/SclService.java:232]: please use a map as suggested in my previous comment

File: sct-commons/src/main/java/org/lfenergy/compas/sct/commons/SclService.java [hunk 8]
```diff
@@ -196,13 +219,70 @@ public List<SclReportItem> updateDoInRef(SCL scd) {
...
+                            if(!tExtRefs.isEmpty()){
+                               ldeviceService.findLdevice(tied, LDEVICE_LDSUIED)
+                                       .ifPresentOrElse(tlDevice -> {
+                                           manageMonitoringLns(tExtRefs.stream().filter(tExtRef -> TServiceType.GOOSE.equals(tExtRef.getServiceType())).toList(), scd, tied, tlDevice, DO_GOCBREF, MonitoringLnClassEnum.LGOS, jaxbContext);
+                                           manageMonitoringLns(tExtRefs.stream().filter(tExtRef -> TServiceType.SMV.equals(tExtRef.getServiceType())).toList(), scd, tied, tlDevice, DO_SVCBREF, MonitoringLnClassEnum.LSVS, jaxbContext);
+                                       }, ()-> errorHanlder.add(SclReportItem.warning(tied.getName(), String.format(MESSAGE_LDEVICE_INST_NOT_FOUND, LDEVICE_LDSUIED, tied.getName()))));
```
Comment (gleizesDor) [inline sct-commons/src/main/java/org/lfenergy/compas/sct/commons/SclService.java:238]: no; it's a blocking problem, please use `orElseThrow`

File: sct-commons/src/main/java/org/lfenergy/compas/sct/commons/SclService.java [hunk 9]
```diff
@@ -196,13 +219,70 @@ public List<SclReportItem> updateDoInRef(SCL scd) {
...
+    public List<SclReportItem> manageMonitoringLns(SCL scd, JAXBContext jaxbContext) {
+        errorHanlder.clear();
+        iedService.getFilteredIeds(scd, ied -> !ied.getName().contains(IED_TEST_NAME))
+                        .forEach(tied -> {
+                            List<TExtRef> tExtRefs = ldeviceService.getLdevices(tied)
+                                    .flatMap(tlDevice -> extRefReaderService.getExtRefs(tlDevice.getLN0()))
+                                    .filter(tExtRef -> tExtRef.isSetServiceType() && tExtRef.isSetSrcCBName()
+                                            && (tExtRef.getServiceType().equals(TServiceType.GOOSE) || tExtRef.getServiceType().equals(TServiceType.SMV)))
+                                    .toList();
+                            if(!tExtRefs.isEmpty()){
```
Comment (gleizesDor) [inline sct-commons/src/main/java/org/lfenergy/compas/sct/commons/SclService.java:233]: use `Optional.ofNullable` with the map instead of this if

File: sct-commons/src/main/java/org/lfenergy/compas/sct/commons/SclService.java [hunk 10]
```diff
@@ -23,17 +29,34 @@
...
+import static org.lfenergy.compas.sct.commons.util.Utils.copySclElement;
 
 @Slf4j
+@RequiredArgsConstructor
 public class SclService implements SclEditor {
 
+    private static final String DO_GOCBREF = "GoCBRef";
+    private static final String DO_SVCBREF = "SvCBRef";
+    private static final String DA_SETSRCREF = "setSrcRef";
+    private static final String MESSAGE_LDEVICE_INST_NOT_FOUND = "LDevice.inst '%s' not found in IED '%s'";
```
Comment (gleizesDor) [inline sct-commons/src/main/java/org/lfenergy/compas/sct/commons/SclService.java:49]: useless

File: sct-commons/src/main/java/org/lfenergy/compas/sct/commons/SclService.java [hunk 11]
```diff
@@ -196,13 +219,70 @@ public List<SclReportItem> updateDoInRef(SCL scd) {
...
+        iedService.getFilteredIeds(scd, ied -> !ied.getName().contains(IED_TEST_NAME))
+                        .forEach(tied -> {
+                            List<TExtRef> tExtRefs = ldeviceService.getLdevices(tied)
+                                    .flatMap(tlDevice -> extRefReaderService.getExtRefs(tlDevice.getLN0()))
+                                    .filter(tExtRef -> tExtRef.isSetServiceType() && tExtRef.isSetSrcCBName()
+                                            && (tExtRef.getServiceType().equals(TServiceType.GOOSE) || tExtRef.getServiceType().equals(TServiceType.SMV)))
+                                    .toList();
+                            if(!tExtRefs.isEmpty()){
+                               ldeviceService.findLdevice(tied, LDEVICE_LDSUIED)
+                                       .ifPresentOrElse(tlDevice -> {
```
Comment (gleizesDor) [inline sct-commons/src/main/java/org/lfenergy/compas/sct/commons/SclService.java:235]: could you rename `tlDevice` in `ldsuiedLdevice` ?

File: sct-commons/src/main/java/org/lfenergy/compas/sct/commons/SclService.java [hunk 12]
```diff
@@ -196,13 +219,70 @@ public List<SclReportItem> updateDoInRef(SCL scd) {
...
+                                           manageMonitoringLns(tExtRefs.stream().filter(tExtRef -> TServiceType.GOOSE.equals(tExtRef.getServiceType())).toList(), scd, tied, tlDevice, DO_GOCBREF, MonitoringLnClassEnum.LGOS, jaxbContext);
+                                           manageMonitoringLns(tExtRefs.stream().filter(tExtRef -> TServiceType.SMV.equals(tExtRef.getServiceType())).toList(), scd, tied, tlDevice, DO_SVCBREF, MonitoringLnClassEnum.LSVS, jaxbContext);
+                                       }, ()-> errorHanlder.add(SclReportItem.warning(tied.getName(), String.format(MESSAGE_LDEVICE_INST_NOT_FOUND, LDEVICE_LDSUIED, tied.getName()))));
+                            }
+                        });
+        return errorHanlder;
+    }
+
+    private void manageMonitoringLns(List<TExtRef> tExtRefs, SCL scd, TIED tied, TLDevice tlDevice, String doName, MonitoringLnClassEnum monitoringLnClassEnum, JAXBContext jaxbContext) {
```
Comment (gleizesDor) [inline sct-commons/src/main/java/org/lfenergy/compas/sct/commons/SclService.java:244]: could you rename `tlDevice` in `ldsuiedLdevice` ?

File: sct-commons/src/main/java/org/lfenergy/compas/sct/commons/SclService.java [hunk 13]
```diff
@@ -196,13 +219,70 @@ public List<SclReportItem> updateDoInRef(SCL scd) {
                 .toList();
     }
 
+
     @Override
-    public List<SclReportItem> manageMonitoringLns(SCL scd) {
```
Comment (gleizesDor) [inline sct-commons/src/main/java/org/lfenergy/compas/sct/commons/SclService.java:200]: here is the modified code : 
```java
@Override
    public List<SclReportItem> manageMonitoringLns(SCL scd, JAXBContext jaxbContext) {
        errorHanlder.clear();
        iedService.getFilteredIeds(scd, ied -> !ied.getName().contains(IED_TEST_NAME))
                .forEach(tied -> {
                    Map<TServiceType, List<TExtRef>> serviceTypeToExtRefs = ldeviceService.getLdevices(tied)
                            .flatMap(tlDevice -> extRefReaderService.getExtRefs(tlDevice.getLN0()))
                            .filter(tExtRef -> tExtRef.isSetServiceType() && tExtRef.isSetSrcCBName() && (tExtRef.getServiceType().equals(TServiceType.GOOSE) || tExtRef.getServiceType().equals(TServiceType.SMV)))
                            .collect(Collectors.groupingBy(TExtRef::getServiceType));
                    TLDevice ldsuiedLdevice = ldeviceService.findLdevice(tied, LDEVICE_LDSUIED).orElseThrow();
                    Optional.ofNullable(serviceTypeToExtRefs.get(TServiceType.GOOSE))
                            .ifPresent(extRefs -> manageMonitoringLns(extRefs, scd, tied, ldsuiedLdevice, DO_GOCBREF, MonitoringLnClassEnum.LGOS, jaxbContext));
                    Optional.ofNullable(serviceTypeToExtRefs.get(TServiceType.SMV))
                            .ifPresent(extRefs -> manageMonitoringLns(extRefs, scd, tied, ldsuiedLdevice, DO_SVCBREF, MonitoringLnClassEnum.LSVS, jaxbContext));
                });
        return errorHanlder;
    }
```

File: sct-commons/src/main/java/org/lfenergy/compas/sct/commons/SclService.java (hunk 8 above)
Comment (samirromdhani) [reply sct-commons/src/main/java/org/lfenergy/compas/sct/commons/SclService.java:238]: In the old version, it's not.
image

**Review by gleizesDor — APPROVED** [review]
